" Pathogen baby!
execute pathogen#infect()

" Map NerdTree to Ctrl-e
map <C-e> :NERDTreeToggle<CR>

" Get rid of those pesky swap files
set nobackup
set nowritebackup
set noswapfile

" Stops indentation on paste into terminal
set paste

 " Indent automatically depending on filetype
filetype indent on
set autoindent

" Turn on line numbering. Turn it off with set nonu
set number

" Set the tap spaces to 4 and expand to spaces
set tabstop=4 softtabstop=0 expandtab shiftwidth=4

" Set syntax on
syntax on

" Case insensitive search
set ic

" Higlhight search
set hls

" Wrap text instead of being on one line
set lbr

" Change colorscheme from default to delek
colorscheme delek

" Limit line length for git commit messages
au FileType gitcommit set tw=72

" Set Jenkinsfile syntax
au BufReadPost Jenkinsfile set syntax=groovy

" Set bosh files syntax
au BufReadPost packaging set syntax=sh
au BufReadPost spec set syntax=yaml

" Set sensible yml syntax
autocmd FileType yaml setlocal ts=4 sts=4 sw=4 expandtab
autocmd FileType yml setlocal ts=4 sts=4 sw=4 expandtab
